const artList = [
    {
        thumb: "../art/sketchbook/Dragon1-smaller-t.jpg",
        url: "../art/sketchbook/Dragon1-smaller.jpg",
        title: "Dragon 1",
        desc: "",
        cat: "sketchbook",
    },
    {
        thumb: "../art/sketchbook/obby+oss-t.png",
        url: "../art/sketchbook/obby+oss.png",
        title: "Obby oss",
        desc: "",
        cat: "sketchbook",
    },
    {
        thumb: "../art/sketchbook/Static2-t.png",
        url: "../art/sketchbook/Static2.png",
        title: "Sketch of webcomic",
        desc: "",
        cat: "sketchbook",
    },
    {
        thumb: "",
        url: "../art/sketchbook/Untitled_Artwork.png",
        title: "Sketch from sketchbook",
        desc: "",
        cat: "sketchbook",
    },
    {
        thumb: "",
        url: "../art/sketchbook/Untitled_Artwork+2(1).png",
        title: "Sketch from sketchbook",
        desc: "",
        cat: "sketchbook",
    },
    {
        thumb: "",
        url: "../art/sketchbook/Untitled_Artwork+2.png",
        title: "Sketch from sketchbook",
        desc: "",
        cat: "sketchbook",
    },
    {
        thumb: "",
        url: "../art/sketchbook/Untitled_Artwork+3(1).png",
        title: "Sketch from sketchbook",
        desc: "",
        cat: "sketchbook",
    },
    {
        thumb: "",
        url: "../art/sketchbook/Untitled_Artwork+3.png",
        title: "Sketch from sketchbook",
        desc: "",
        cat: "sketchbook",
    },
    {
        thumb: "",
        url: "../art/sketchbook/Untitled_Artwork+4(1).png",
        title: "Sketch from sketchbook",
        desc: "",
        cat: "sketchbook",
    },
    {
        thumb: "",
        url: "../art/sketchbook/Untitled_Artwork+5(1).png",
        title: "Sketch from sketchbook",
        desc: "",
        cat: "sketchbook",
    },
    {
        thumb: "../art/sketchbook/Untitled_Artwork+5-t.png",
        url: "../art/sketchbook/Untitled_Artwork+5.png",
        title: "Sketch from sketchbook",
        desc: "",
        cat: "sketchbook",
    },
    {
        thumb: "",
        url: "../art/sketchbook/Untitled_Artwork+6(1).png",
        title: "Sketch from sketchbook",
        desc: "",
        cat: "sketchbook",
    },
    
    {
        thumb: "../art/witch-tools/thumb.jpg",
        url: "../art/witch-tools/",
        title: "Witch Tools",
        desc: "",
        cat: "",
    },
    {
        thumb: "../art/albitecita/thumb.jpg",
        url: "../art/albitecita/",
        title: "Albitecita",
        desc: "",
        cat: "",
    },
];