const artList = [
    {
        thumb: "../art/sketchbook/Dragon1-smaller-t.jpg",
        url: "../art/sketchbook/Dragon1-smaller.jpg",
        title: "Dragon 1",
        desc: "",
        cat: "sketchbook",
    },
    {
        thumb: "../art/sketchbook/obby+oss-t.png",
        url: "../art/sketchbook/obby+oss.png",
        title: "Obby oss",
        desc: "",
        cat: "sketchbook",
    },
    {
        thumb: "../art/sketchbook/Static2-t.png",
        url: "../art/sketchbook/Static2.png",
        title: "Sketch of webcomic",
        desc: "",
        cat: "sketchbook",
    },
    {
        thumb: "",
        url: "../art/sketchbook/Untitled_Artwork.png",
        title: "Sketch from sketchbook",
        desc: "",
        cat: "sketchbook",
    },
    {
        thumb: "",
        url: "../art/sketchbook/Untitled_Artwork+2(1).png",
        title: "Sketch from sketchbook",
        desc: "",
        cat: "sketchbook",
    },
    {
        thumb: "",
        url: "../art/sketchbook/Untitled_Artwork+2.png",
        title: "Sketch from sketchbook",
        desc: "",
        cat: "sketchbook",
    },
    {
        thumb: "",
        url: "../art/sketchbook/Untitled_Artwork+3(1).png",
        title: "Sketch from sketchbook",
        desc: "",
        cat: "sketchbook",
    },
    {
        thumb: "",
        url: "../art/sketchbook/Untitled_Artwork+3.png",
        title: "Sketch from sketchbook",
        desc: "",
        cat: "sketchbook",
    },
    {
        thumb: "",
        url: "../art/sketchbook/Untitled_Artwork+4(1).png",
        title: "Sketch from sketchbook",
        desc: "",
        cat: "sketchbook",
    },
    {
        thumb: "",
        url: "../art/sketchbook/Untitled_Artwork+5(1).png",
        title: "Sketch from sketchbook",
        desc: "",
        cat: "sketchbook",
    },
    {
        thumb: "../art/sketchbook/Untitled_Artwork+5-t.png",
        url: "../art/sketchbook/Untitled_Artwork+5.png",
        title: "Sketch from sketchbook",
        desc: "",
        cat: "sketchbook",
    },
    {
        thumb: "",
        url: "../art/sketchbook/Untitled_Artwork+6(1).png",
        title: "Sketch from sketchbook",
        desc: "",
        cat: "sketchbook",
    },
    
    {
        thumb: "../art/witch-tools/thumb.webp",
        url: "../art/witch-tools/",
        title: "Witch Tools",
        desc: "",
        cat: "",
    },
    {
        thumb: "../art/albitecita/thumb.jpg",
        url: "../art/albitecita/",
        title: "Albitecita",
        desc: "",
        cat: "",
    },
    {
        thumb: "../art/spriggan-thumbnail.webp",
        url: "https://youtu.be/dBWXoE5ANZQ",
        title: "Spriggan - The fairy villian of Penwith Folklore",
        desc: "The protector of ancient cairns and barrows of the ancient Cornish moorland, the evil ghosts of giants that haunt the stones. The Spriggan is a mythical Piskie creature from Penwith, Cornwall. THIS IS MY ART PROJECT FOR THIS WEEK OK THANKS",
        cat: "",
    },
    {
        thumb: "../art/albitecita/creature-thumb.webp",
        url: "https://youtube.com/shorts/lzBRYMiQkW0?feature=share",
        title: "A creature looking through your window",
        desc: "",
        cat: "",
    },
];