const artList = [
    {
        thumb: "../art/sketchbook/jester-thumb.webp",
        url: "../art/sketchbook/jester.webp",
        title: "Sketch from sketchbook",
        desc: "",
        cat: "sketchbook",
    },
    {
        thumb: "../art/sketchbook/20250123_143816-thumb.webp",
        url:   "../art/sketchbook/20250123_143816.webp",
        title: "Sketch from sketchbook",
        desc: "",
        cat: "sketchbook",
    },
    {
        thumb: "../art/sketchbook/20250123_143846-thumb.webp",
        url:   "../art/sketchbook/20250123_143846.webp",
        title: "Sketch from sketchbook",
        desc: "",
        cat: "sketchbook",
    },
    {
        thumb: "../art/sketchbook/20250123_143806-thumb.webp",
        url:   "../art/sketchbook/20250123_143806.webp",
        title: "Sketch from sketchbook",
        desc: "",
        cat: "sketchbook",
    },
    {
        thumb: "",
        url: "../art/sketchbook/Untitled_Artwork+3.png",
        title: "Sketch from procreate sketchbook",
        desc: "",
        cat: "sketchbook",
    },
    {
        thumb: "../art/sketchbook/20250123_143901-thumb.webp",
        url:   "../art/sketchbook/20250123_143901.webp",
        title: "Sketch from sketchbook",
        desc: "",
        cat: "sketchbook",
    },
    {
        thumb: "../art/sketchbook/Untitled_Artwork+5-t.png",
        url: "../art/sketchbook/Untitled_Artwork+5.png",
        title: "Sketch from procreate sketchbook",
        desc: "",
        cat: "sketchbook",
    },
    {
        thumb: "",
        url: "../art/sketchbook/Untitled_Artwork+2(1).png",
        title: "Sketch from procreate sketchbook",
        desc: "",
        cat: "sketchbook",
    },
    {
        thumb: "../art/sketchbook/20250123_144014-thumb.webp",
        url:   "../art/sketchbook/20250123_144014.webp",
        title: "Sketch from sketchbook",
        desc: "",
        cat: "sketchbook",
    },
    {
        thumb: "../art/sketchbook/Untitled_Artwork+9-thumb.webp",
        url: "../art/sketchbook/Untitled_Artwork+9.webp",
        title: "Sketch from procreate sketchbook",
        desc: "",
        cat: "sketchbook",
    },
    {
        thumb: "../art/sketchbook/20250123_144027-thumb.webp",
        url:   "../art/sketchbook/20250123_144027.webp",
        title: "Sketch from sketchbook",
        desc: "",
        cat: "sketchbook",
    },
    {
        thumb: false,
        url: "../art/sketchbook/Untitled_Artwork+11.png",
        title: "Sketch from procreate sketchbook",
        desc: "",
        cat: "sketchbook",
    },
    {
        thumb: "../art/sketchbook/Untitled_Artwork+13-thumb.webp",
        url: "../art/sketchbook/Untitled_Artwork+13.webp",
        title: "Sketch from procreate sketchbook",
        desc: "",
        cat: "sketchbook",
    },
    {
        thumb: false,
        url: "../art/sketchbook/Untitled_Artwork+14.png",
        title: "Sketch from procreate sketchbook",
        desc: "",
        cat: "sketchbook",
    },
    {
        thumb: "../art/sketchbook/20250123_144255-thumb.webp",
        url:   "../art/sketchbook/20250123_144255.webp",
        title: "Sketch from sketchbook",
        desc: "",
        cat: "sketchbook",
    },
    {
        thumb: "../art/sketchbook/Untitled_Artwork+30-thumb.webp",
        url: "../art/sketchbook/Untitled_Artwork+30.webp",
        title: "Sketch from procreate sketchbook",
        desc: "",
        cat: "sketchbook",
    },
    {
        thumb: "../art/sketchbook/20250123_144320-thumb.webp",
        url:   "../art/sketchbook/20250123_144320.webp",
        title: "Sketch from sketchbook",
        desc: "",
        cat: "sketchbook",
    },
    {
        thumb: "../art/sketchbook/20250124_142540-thumb.webp",
        url:   "../art/sketchbook/20250124_142540.webp",
        title: "Sketch from sketchbook",
        desc: "",
        cat: "sketchbook",
    },
    {
        thumb: "../art/sketchbook/20250123_143717-thumb.webp",
        url: "../art/sketchbook/20250123_143717.webp",
        title: "Sketch from sketchbook",
        desc: "",
        cat: "sketchbook",
    },
    {
        thumb: "../art/sketchbook/Untitled_Artwork+26-thumb.webp",
        url: "../art/sketchbook/Untitled_Artwork+26.webp",
        title: "Matt Berry arguing with himself",
        desc: "",
        cat: "sketchbook",
    },
    {
        thumb: "../art/sketchbook/obby+oss-t.png",
        url: "../art/sketchbook/obby+oss.png",
        title: "Obby oss",
        desc: "",
        cat: "sketchbook",
    },
    {
        thumb: "../art/sketchbook/Static2-t.png",
        url: "../art/sketchbook/Static2.png",
        title: "Sketch of webcomic",
        desc: "",
        cat: "sketchbook",
    },
    
    {
        thumb: "../art/witch-tools/thumb.webp",
        url: "../art/witch-tools/",
        title: "Witch Tools",
        desc: "Interactive art project. You are a witch who has created a set of magical tools deep in the woods. How does it work? And what spirits reside inside?",
        cat: "",
    },
    {
        thumb: "../art/jester-paint-thumb.webp",
        url: "../art/jester-paint.webp",
        title: "Jester",
        desc: "",
        cat: "",
    },
    {
        thumb: "",
        url: "../art/weddinginvite.webp",
        title: "Wedding invite",
        desc: "",
        cat: "",
    },
    {
        thumb: "",
        url: "../art/sketchbook/Untitled_Artwork+5(1).png",
        title: "Roller derby",
        desc: "",
        cat: "",
    },
    {
        thumb: "../art/spriggan-thumbnail.webp",
        url: "https://youtu.be/dBWXoE5ANZQ",
        title: "Spriggan - The fairy villian of Penwith Folklore",
        desc: "The protector of ancient cairns and barrows of the ancient Cornish moorland, the evil ghosts of giants that haunt the stones. The Spriggan is a mythical Piskie creature from Penwith, Cornwall.",
        cat: "",
    },
    {
        thumb: "",
        url: "../art/weddingmenufront.webp",
        title: "Wedding menu",
        desc: "",
        cat: "",
    },
    {
        thumb: "",
        url: "../art/weddingmenuback.webp",
        title: "",
        desc: "",
        cat: "",
    },
    {
        thumb: "../art/creature-thumb.webp",
        url: "https://youtube.com/shorts/lzBRYMiQkW0?feature=share",
        title: "A creature looking through your window",
        desc: "",
        cat: "",
    },
    {
        thumb: "../art/sketchbook/Dragon1-smaller-t.webp",
        url: "../art/sketchbook/Dragon1-smaller.webp",
        title: "Dragon",
        desc: "",
        cat: "",
    },
    {
        thumb: "../art/Static-thumb.webp",
        url: "../art/Static.webp",
        title: "Static, 0-1",
        desc: "",
        cat: "",
    },
    {
        thumb: "../art/church-thumb.webp",
        url: "../art/church.webp",
        title: "Cornish Church",
        desc: "",
        cat: "",
    },
    {
        thumb: "",
        url: "../art/domestic_hedgehog.webp",
        title: "",
        desc: "",
        cat: "",
    },
];